name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare
        run: |
          sudo apt-get update
          mkdir -p dist
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/C%2B%2B.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/C.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/Global/Archives.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/Global/Linux.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/Global/macOS.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/Global/Windows.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/github/gitignore/main/Go.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          curl -LR -o- "https://raw.githubusercontent.com/seiflotfy/cuckoofilter/master/.gitignore" | sed 's/\r//' | sort -u | grep -vE '^#|^$' >> dist/gitignore
          echo -e "!go.mod\n!go.sum\n.idea/" >> dist/gitignore
          sort -u dist/gitignore | grep -vE '^#|^$' > .gitignore
          rm -rf dist
          find -name '*test.go' | xargs rm -rf
          find -name 'go.mod' | xargs perl -pi -e 's|go 1.*|go 1.20|g'
          find -name 'go.mod' | xargs perl -pi -e 's|/seiflotfy/cuckoofilter|/luoluodaduan/cuckoofilter|g'
          find -name '*.go' | xargs perl -pi -e 's|/seiflotfy/cuckoofilter|/luoluodaduan/cuckoofilter|g'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Update
        run: |
          go install mvdan.cc/gofumpt@master
          go install github.com/daixiang0/gci@latest
          find -name '*.go' | xargs gofumpt -l -w
          find -name '*.go' | xargs gci write -s standard -s default
          go get -u all
          go mod tidy

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
