name: Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Prepare
        run: |
          sudo apt-get update
          rm -rf .github/workflows/delete.yml
          find -name '*test.go' | xargs rm -rf
          find -name 'go.mod' | xargs perl -pi -e 's|/seiflotfy/cuckoofilter|/luoluodaduan/cuckoofilter|g'
          find -name 'go.mod' | xargs perl -pi -e 's|go 1.*|go 1.22|g'
          find -name '*.go' | xargs perl -pi -e 's|/seiflotfy/cuckoofilter|/luoluodaduan/cuckoofilter|g'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Update
        run: |
          go install mvdan.cc/gofumpt@master
          go install github.com/daixiang0/gci@master
          find -name '*.go' | xargs gofumpt -e -l -w
          find -name '*.go' | xargs gci write -s standard -s default
          go get -u
          go mod tidy

      - name: Commit Files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
